'use client';

import {
  ServerCreateProvider,
  ServerJoinedTeamProvider,
  ServerStateProvider,
  ProfileProvider,
  MeetingProvider,
} from '../../../context';
import { LoadingOverlay } from '../../components';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export function RootLayoutWrapper({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ServerCreateProvider>
          <ServerJoinedTeamProvider>
            <ServerStateProvider>
              <ProfileProvider>
                <MeetingProvider>{children}</MeetingProvider>
              </ProfileProvider>
              <LoadingOverlay />
            </ServerStateProvider>
          </ServerJoinedTeamProvider>
        </ServerCreateProvider>
      </body>
    </html>
  );
}
