'use client';

import {
  ServerCreateProvider,
  ServerJoinedTeamProvider,
  ServerStateProvider,
  ServerModalProvider,
  ServerLoadingProvider,
} from '../../../context';
import { LoadingOverlay } from '../../components';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export function RootLayoutWrapper({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ServerCreateProvider>
          <ServerJoinedTeamProvider>
            <ServerModalProvider>
              <ServerStateProvider>
                <ServerLoadingProvider>
                  {children}
                  <LoadingOverlay />
                </ServerLoadingProvider>
              </ServerStateProvider>
            </ServerModalProvider>
          </ServerJoinedTeamProvider>
        </ServerCreateProvider>
      </body>
    </html>
  );
}
