import './global.css';
import {
  ServerCreateProvider,
  ServerJoinedTeamProvider,
  ServerStateProvider,
} from '@meezy/ui';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ServerCreateProvider>
          <ServerJoinedTeamProvider>
            <ServerStateProvider>{children}</ServerStateProvider>
          </ServerJoinedTeamProvider>
        </ServerCreateProvider>
      </body>
    </html>
  );
}
